version: '3'
  
services:
  map:
    # image: overv/openstreetmap-tile-server
    build: ./
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
      - ./osm-updates:/data/updates # edit this line as you like
    ports:
      - "8080:80"
      - "5432:5432"
    environment:
      - THREADS=4
      - "OSM2PGSQL_EXTRA_ARGS=-C 4096"
      - TZ=Europe/Rome
    command: "run"

volumes:
  osm-data:
    external: true
  osm-tiles:
    external: true

