version: '3'
  
services:
  map:
    # image: overv/openstreetmap-tile-server
    build: ./
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
      - ./osm-updates:/data/updates
    ports:
      - "8080:80"
      - "5432:5432"
    command: "run"

volumes:
  osm-data:
    external: true
  osm-tiles:
    external: true

